In [1]:
from torch import nn

In [2]:
loss = nn.CrossEntropyLoss()

In [3]:
import torch

In [5]:
input = torch.randn(3, 5, requires_grad=True)

In [6]:
input

tensor([[ 1.6302, -1.6460, -0.2522, -0.4300, -0.2670],
        [-0.8821, -2.2035, -0.1391,  1.9096, -0.9581],
        [ 1.3239,  0.0099,  1.3565,  0.6273,  2.8026]], requires_grad=True)

In [9]:
target = torch.empty(3, dtype=torch.long).random_(5)

In [10]:
target

tensor([4, 3, 4])

In [11]:
output = loss(input, target)

In [12]:
output.backward()

In [13]:
output

tensor(1.0027, grad_fn=<NllLossBackward0>)

In [14]:
input = torch.randn(3, 5, requires_grad=True)

In [15]:
input

tensor([[-0.9642,  0.1543,  1.4067, -1.4012, -1.5670],
        [ 0.2521, -1.3227, -0.4833, -1.4289,  2.4895],
        [ 0.0920, -1.3687, -2.4273,  0.3875, -0.6743]], requires_grad=True)

In [16]:
target = torch.randn(3, 5).softmax(dim=1)

In [17]:
target

tensor([[0.0247, 0.6417, 0.0784, 0.0206, 0.2346],
        [0.1719, 0.3919, 0.0806, 0.2279, 0.1277],
        [0.3802, 0.1042, 0.2082, 0.0977, 0.2096]])

In [18]:
output = loss(input, target)

In [19]:
output

tensor(2.3857, grad_fn=<DivBackward1>)

In [20]:
output.backward()

In [21]:
output

tensor(2.3857, grad_fn=<DivBackward1>)