In [1]:
import torch

In [2]:
a = torch.randn(4, 4)

In [3]:
a

tensor([[ 4.5902e-01, -1.7777e-01,  2.8145e-01, -1.0434e+00],
        [ 6.4630e-01,  1.0731e+00, -9.9784e-01,  1.0956e+00],
        [ 1.3761e-01,  4.3819e-01,  1.1196e+00, -2.9732e+00],
        [-9.9236e-01,  4.4516e-01, -1.7149e-03, -1.1496e+00]])

In [4]:
torch.chunk(a, 2)

(tensor([[ 0.4590, -0.1778,  0.2814, -1.0434],
         [ 0.6463,  1.0731, -0.9978,  1.0956]]),
 tensor([[ 1.3761e-01,  4.3819e-01,  1.1196e+00, -2.9732e+00],
         [-9.9236e-01,  4.4516e-01, -1.7149e-03, -1.1496e+00]]))

In [5]:
torch.chunk(a, 2, 0)

(tensor([[ 0.4590, -0.1778,  0.2814, -1.0434],
         [ 0.6463,  1.0731, -0.9978,  1.0956]]),
 tensor([[ 1.3761e-01,  4.3819e-01,  1.1196e+00, -2.9732e+00],
         [-9.9236e-01,  4.4516e-01, -1.7149e-03, -1.1496e+00]]))

In [6]:
torch.chunk(a, 2, 1)

(tensor([[ 0.4590, -0.1778],
         [ 0.6463,  1.0731],
         [ 0.1376,  0.4382],
         [-0.9924,  0.4452]]),
 tensor([[ 2.8145e-01, -1.0434e+00],
         [-9.9784e-01,  1.0956e+00],
         [ 1.1196e+00, -2.9732e+00],
         [-1.7149e-03, -1.1496e+00]]))