In [1]:
import torch

In [2]:
x = torch.randn(2, 2)

In [3]:
x

tensor([[ 0.2296,  1.7469],
        [ 0.1455, -0.4656]])

In [4]:
torch.sigmoid(x)

tensor([[0.5571, 0.8516],
        [0.5363, 0.3856]])

In [5]:
x

tensor([[ 0.2296,  1.7469],
        [ 0.1455, -0.4656]])

In [6]:
torch.sqrt(x)

tensor([[0.4792, 1.3217],
        [0.3815,    nan]])