In [1]:
import torch

In [2]:
x = torch.randn(4, 5)

In [3]:
x

tensor([[-0.6463,  1.3836,  2.3073, -0.8254,  0.1415],
        [ 1.2465, -0.0366, -1.4175, -1.3118, -2.4377],
        [-0.8946, -0.2246,  0.2709,  0.5813,  0.4900],
        [ 0.0614,  0.9231,  1.1803, -0.7082,  0.5932]])

In [4]:
torch.cat((x, x))

tensor([[-0.6463,  1.3836,  2.3073, -0.8254,  0.1415],
        [ 1.2465, -0.0366, -1.4175, -1.3118, -2.4377],
        [-0.8946, -0.2246,  0.2709,  0.5813,  0.4900],
        [ 0.0614,  0.9231,  1.1803, -0.7082,  0.5932],
        [-0.6463,  1.3836,  2.3073, -0.8254,  0.1415],
        [ 1.2465, -0.0366, -1.4175, -1.3118, -2.4377],
        [-0.8946, -0.2246,  0.2709,  0.5813,  0.4900],
        [ 0.0614,  0.9231,  1.1803, -0.7082,  0.5932]])

In [5]:
torch.cat((x, x, x), 1)

tensor([[-0.6463,  1.3836,  2.3073, -0.8254,  0.1415, -0.6463,  1.3836,  2.3073,
         -0.8254,  0.1415, -0.6463,  1.3836,  2.3073, -0.8254,  0.1415],
        [ 1.2465, -0.0366, -1.4175, -1.3118, -2.4377,  1.2465, -0.0366, -1.4175,
         -1.3118, -2.4377,  1.2465, -0.0366, -1.4175, -1.3118, -2.4377],
        [-0.8946, -0.2246,  0.2709,  0.5813,  0.4900, -0.8946, -0.2246,  0.2709,
          0.5813,  0.4900, -0.8946, -0.2246,  0.2709,  0.5813,  0.4900],
        [ 0.0614,  0.9231,  1.1803, -0.7082,  0.5932,  0.0614,  0.9231,  1.1803,
         -0.7082,  0.5932,  0.0614,  0.9231,  1.1803, -0.7082,  0.5932]])

In [6]:
torch.cat((x, x), 0)

tensor([[-0.6463,  1.3836,  2.3073, -0.8254,  0.1415],
        [ 1.2465, -0.0366, -1.4175, -1.3118, -2.4377],
        [-0.8946, -0.2246,  0.2709,  0.5813,  0.4900],
        [ 0.0614,  0.9231,  1.1803, -0.7082,  0.5932],
        [-0.6463,  1.3836,  2.3073, -0.8254,  0.1415],
        [ 1.2465, -0.0366, -1.4175, -1.3118, -2.4377],
        [-0.8946, -0.2246,  0.2709,  0.5813,  0.4900],
        [ 0.0614,  0.9231,  1.1803, -0.7082,  0.5932]])