In [12]:
import torch

In [13]:
torch.Tensor([[11, 12], [23, 24]])

tensor([[11., 12.],
        [23., 24.]])

In [14]:
torch.gather(torch.Tensor([[11, 12], [23, 24]]), 1, torch.LongTensor([[0, 0], [1, 0]]))

tensor([[11., 11.],
        [24., 23.]])

In [15]:
torch.gather(torch.Tensor([[11, 12], [23, 24]]), 0, torch.LongTensor([[0, 0], [1, 0]]))

tensor([[11., 12.],
        [23., 12.]])

In [16]:
torch.gather(torch.Tensor([[11, 12, 13, 14, 15], [23, 24, 25, 26, 27]]), 0, torch.LongTensor([[0, 0, 0, 0, 0], [1, 0, 1, 1, 0]]))

tensor([[11., 12., 13., 14., 15.],
        [23., 12., 25., 26., 15.]])