In [1]:
import torch

In [2]:
intercept = torch.randn(1)

In [3]:
intercept

tensor([-2.3132])

In [4]:
x = torch.randn(2, 2)

In [5]:
x

tensor([[ 0.8993,  0.6668],
        [-0.3282,  1.5359]])

In [6]:
beta = 0.7456

In [7]:
beta

0.7456

In [8]:
torch.mul(intercept, x)

tensor([[-2.0803, -1.5424],
        [ 0.7591, -3.5527]])

In [9]:
torch.mul(x, beta)

tensor([[ 0.6705,  0.4972],
        [-0.2447,  1.1451]])

In [10]:
torch.add(torch.mul(intercept, x), torch.mul(x, beta))

tensor([[-1.4098, -1.0453],
        [ 0.5144, -2.4076]])