In [1]:
import torch

In [2]:
torch.manual_seed(1234)

In [3]:
torch.randn(5, 5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [4]:
torch.manual_seed(1234)

In [5]:
torch.ceil(torch.randn(5, 5))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])

In [6]:
torch.floor(torch.randn(5, 5))

tensor([[ 0.,  0.,  1., -1.,  0.],
        [ 0., -1.,  1., -1.,  0.],
        [-1.,  0., -2.,  0.,  0.],
        [-1., -1., -2.,  0.,  0.],
        [-1., -1.,  0.,  0., -3.]])