In [1]:
import torch

In [3]:
x = torch.randn(2, 2)

In [4]:
x

tensor([[-2.3004, -2.5599],
        [-0.9068,  0.3080]])

In [5]:
torch.log(x)

tensor([[    nan,     nan],
        [    nan, -1.1776]])

In [6]:
torch.pow(x, 2)

tensor([[5.2920, 6.5533],
        [0.8223, 0.0949]])