In [1]:
import torch

In [2]:
torch.nonzero(torch.tensor([10, 00, 23, 0, 0.0]))

tensor([[0],
        [2]])

In [3]:
torch.split(torch.tensor([12, 21, 34, 32, 45, 54, 56, 65]), 2)

(tensor([12, 21]), tensor([34, 32]), tensor([45, 54]), tensor([56, 65]))

In [4]:
torch.split(torch.tensor([12, 21, 34, 32, 45, 54, 56, 65]), 3)

(tensor([12, 21, 34]), tensor([32, 45, 54]), tensor([56, 65]))