In [1]:
import torch

In [2]:
d = torch.randn(4, 5)

In [3]:
d

tensor([[ 0.3441,  1.2460,  0.1514,  1.1275, -1.1150],
        [-1.5673,  0.4682, -0.4775,  2.0064, -1.5704],
        [-1.7395,  0.9882,  0.0948,  0.2307,  0.3488],
        [-0.5216, -2.2972,  0.3321, -2.0335, -0.8470]])

In [4]:
torch.argmin(d, dim=1)

tensor([4, 4, 0, 1])

In [5]:
torch.argmax(d, dim=1)

tensor([1, 3, 1, 2])