In [1]:
import torch

In [2]:
torch.manual_seed(1234)

In [4]:
x = torch.randn(5, 5)

In [6]:
x

tensor([[ 0.0190,  0.0220,  1.1532, -0.3393,  0.1559],
        [ 0.8966, -0.2968,  1.5985, -0.0496,  0.1825],
        [-0.0737,  0.3147, -1.0369,  0.2100,  0.6144],
        [-0.0552, -0.6125, -1.7970,  0.8728,  0.7670],
        [-0.1138, -0.9428,  0.7540,  0.1365, -2.3332]])

In [7]:
torch.floor(x)

tensor([[ 0.,  0.,  1., -1.,  0.],
        [ 0., -1.,  1., -1.,  0.],
        [-1.,  0., -2.,  0.,  0.],
        [-1., -1., -2.,  0.,  0.],
        [-1., -1.,  0.,  0., -3.]])

In [5]:
torch.clamp(torch.floor(x), min=-0.3, max=0.4)

tensor([[ 0.0000,  0.0000,  0.4000, -0.3000,  0.0000],
        [ 0.0000, -0.3000,  0.4000, -0.3000,  0.0000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000],
        [-0.3000, -0.3000, -0.3000,  0.0000,  0.0000],
        [-0.3000, -0.3000,  0.0000,  0.0000, -0.3000]])

In [8]:
torch.clamp(torch.floor(x), min=-0.3)

tensor([[ 0.0000,  0.0000,  1.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000,  0.0000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000],
        [-0.3000, -0.3000, -0.3000,  0.0000,  0.0000],
        [-0.3000, -0.3000,  0.0000,  0.0000, -0.3000]])

In [9]:
torch.clamp(torch.floor(x), max=0.3)

tensor([[ 0.0000,  0.0000,  0.3000, -1.0000,  0.0000],
        [ 0.0000, -1.0000,  0.3000, -1.0000,  0.0000],
        [-1.0000,  0.0000, -2.0000,  0.0000,  0.0000],
        [-1.0000, -1.0000, -2.0000,  0.0000,  0.0000],
        [-1.0000, -1.0000,  0.0000,  0.0000, -3.0000]])