In [1]:
import torch

In [2]:
x = torch.randn(4, 5)

In [3]:
x

tensor([[ 0.6771,  0.0639, -0.4088, -0.3287,  0.0394],
        [-0.4094,  0.7559, -0.1122, -0.8051,  0.4162],
        [-1.9714,  0.6883, -0.1474,  0.0720,  1.0881],
        [ 0.0518,  0.1496, -0.4576, -1.0326,  1.8557]])

In [4]:
x.t()

tensor([[ 0.6771, -0.4094, -1.9714,  0.0518],
        [ 0.0639,  0.7559,  0.6883,  0.1496],
        [-0.4088, -0.1122, -0.1474, -0.4576],
        [-0.3287, -0.8051,  0.0720, -1.0326],
        [ 0.0394,  0.4162,  1.0881,  1.8557]])

In [5]:
x.transpose(1, 0)

tensor([[ 0.6771, -0.4094, -1.9714,  0.0518],
        [ 0.0639,  0.7559,  0.6883,  0.1496],
        [-0.4088, -0.1122, -0.1474, -0.4576],
        [-0.3287, -0.8051,  0.0720, -1.0326],
        [ 0.0394,  0.4162,  1.0881,  1.8557]])

In [6]:
torch.unbind(x, 1)

(tensor([ 0.6771, -0.4094, -1.9714,  0.0518]),
 tensor([0.0639, 0.7559, 0.6883, 0.1496]),
 tensor([-0.4088, -0.1122, -0.1474, -0.4576]),
 tensor([-0.3287, -0.8051,  0.0720, -1.0326]),
 tensor([0.0394, 0.4162, 1.0881, 1.8557]))

In [7]:
torch.unbind(x)

(tensor([ 0.6771,  0.0639, -0.4088, -0.3287,  0.0394]),
 tensor([-0.4094,  0.7559, -0.1122, -0.8051,  0.4162]),
 tensor([-1.9714,  0.6883, -0.1474,  0.0720,  1.0881]),
 tensor([ 0.0518,  0.1496, -0.4576, -1.0326,  1.8557]))