In [1]:
import torch

In [2]:
x = torch.randn(4, 5)

In [3]:
torch.add(x, 20)

tensor([[19.0281, 20.4784, 19.0961, 19.9266, 18.9415],
        [20.0720, 17.2433, 19.8123, 19.9099, 19.5800],
        [19.5637, 20.2140, 17.4826, 21.4642, 19.5709],
        [20.6016, 21.9142, 18.2219, 19.1960, 19.1654]])

In [4]:
x

tensor([[-0.9719,  0.4784, -0.9039, -0.0734, -1.0585],
        [ 0.0720, -2.7567, -0.1877, -0.0901, -0.4200],
        [-0.4363,  0.2140, -2.5174,  1.4642, -0.4291],
        [ 0.6016,  1.9142, -1.7781, -0.8040, -0.8346]])

In [5]:
torch.mul(x, 2)

tensor([[-1.9437,  0.9567, -1.8077, -0.1467, -2.1171],
        [ 0.1440, -5.5134, -0.3753, -0.1801, -0.8400],
        [-0.8725,  0.4280, -5.0347,  2.9284, -0.8582],
        [ 1.2031,  3.8285, -3.5562, -1.6080, -1.6691]])

In [6]:
x

tensor([[-0.9719,  0.4784, -0.9039, -0.0734, -1.0585],
        [ 0.0720, -2.7567, -0.1877, -0.0901, -0.4200],
        [-0.4363,  0.2140, -2.5174,  1.4642, -0.4291],
        [ 0.6016,  1.9142, -1.7781, -0.8040, -0.8346]])