In [1]:
import torch

In [2]:
a = torch.randn(4, 4)

In [3]:
a

tensor([[ 0.0486, -0.4417, -0.4725,  1.4933],
        [-0.0898, -0.4093,  0.3874,  0.3380],
        [-0.5195,  0.1926, -1.9054,  0.0478],
        [-0.0219, -0.2120, -0.1766, -0.0214]])

In [4]:
indices = torch.LongTensor([0, 2])

In [5]:
torch.index_select(a, 0, indices)

tensor([[ 0.0486, -0.4417, -0.4725,  1.4933],
        [-0.5195,  0.1926, -1.9054,  0.0478]])

In [6]:
torch.index_select(a, 1, indices)

tensor([[ 0.0486, -0.4725],
        [-0.0898,  0.3874],
        [-0.5195, -1.9054],
        [-0.0219, -0.1766]])