In [1]:
import torch

In [2]:
torch.mean(torch.tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.]))

tensor(45.9167)

In [3]:
d = torch.randn(4, 5)

In [4]:
d

tensor([[ 1.1023, -0.2521, -0.1671,  0.2819,  0.7779],
        [-0.0386,  0.0500,  0.8849, -0.9988,  1.9671],
        [-0.5616, -0.9799,  0.5542, -0.6574,  1.8517],
        [-0.6818,  0.7967, -0.8463, -1.3720, -0.9040]])

In [5]:
torch.mean(d, dim=0)

tensor([-0.0449, -0.0963,  0.1064, -0.6866,  0.9232])

In [6]:
torch.mean(d, dim=1)

tensor([ 0.3486,  0.3729,  0.0414, -0.6015])

In [11]:
torch.mean(torch.tensor([-0.0386,  0.0500,  0.8849, -0.9988,  1.9671]))

tensor(0.3729)