In [1]:
import torch

In [2]:
torch.Tensor([10, 10, 13, 10, 34, 45, 65, 67, 87, 89, 87, 34])

tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.])

In [6]:
torch.multinomial(torch.tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.]), 3)

tensor([6, 8, 7])

In [15]:
torch.multinomial(torch.tensor([10., 10., 13., 10., 34., 45., 65., 67., 87., 89., 87., 34.]), 5, replacement=True)

tensor([ 6, 10,  7,  9,  9])