In [1]:
import torch

In [2]:
mat1 = torch.FloatTensor(4, 4).uniform_(0, 1)

In [3]:
mat1

tensor([[0.9266, 0.7827, 0.2471, 0.9294],
        [0.0540, 0.1511, 0.4529, 0.3706],
        [0.8870, 0.3989, 0.5832, 0.8617],
        [0.7269, 0.5526, 0.2805, 0.2048]])

In [4]:
mat2 = torch.FloatTensor(5, 4).uniform_(0, 1)

In [5]:
mat2

tensor([[0.5737, 0.5840, 0.1286, 0.3772],
        [0.1214, 0.3855, 0.4431, 0.9869],
        [0.7324, 0.9596, 0.2269, 0.1207],
        [0.7028, 0.5890, 0.6773, 0.2998],
        [0.3209, 0.4999, 0.0984, 0.6596]])

In [6]:
mat1 + mat2

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 0

In [7]:
mat1 * mat1

tensor([[0.8587, 0.6127, 0.0611, 0.8637],
        [0.0029, 0.0228, 0.2051, 0.1373],
        [0.7867, 0.1591, 0.3402, 0.7425],
        [0.5283, 0.3053, 0.0787, 0.0420]])