In [1]:
import torch

In [5]:
mat1 = torch.FloatTensor(4, 4).uniform_(0, 1)

In [6]:
mat1

tensor([[0.5468, 0.1778, 0.4480, 0.5566],
        [0.8964, 0.9685, 0.4558, 0.9977],
        [0.0166, 0.5548, 0.2433, 0.7819],
        [0.4518, 0.5381, 0.9541, 0.8290]])

In [7]:
mat2 = torch.FloatTensor(5, 4).uniform_(0, 1)

In [8]:
mat2

tensor([[0.9118, 0.4237, 0.7060, 0.3372],
        [0.6695, 0.2520, 0.8409, 0.0578],
        [0.5613, 0.9566, 0.5450, 0.0556],
        [0.5068, 0.3618, 0.5411, 0.4894],
        [0.7332, 0.4136, 0.8484, 0.6287]])

In [9]:
vec1 = torch.FloatTensor(4).uniform_(0, 1)

In [10]:
vec1

tensor([0.1123, 0.7166, 0.9619, 0.1515])

In [11]:
mat1 + 10.5

tensor([[11.0468, 10.6778, 10.9480, 11.0566],
        [11.3964, 11.4685, 10.9558, 11.4977],
        [10.5166, 11.0548, 10.7433, 11.2819],
        [10.9518, 11.0381, 11.4541, 11.3290]])

In [12]:
mat2 - 0.20

tensor([[ 0.7118,  0.2237,  0.5060,  0.1372],
        [ 0.4695,  0.0520,  0.6409, -0.1422],
        [ 0.3613,  0.7566,  0.3450, -0.1444],
        [ 0.3068,  0.1618,  0.3411,  0.2894],
        [ 0.5332,  0.2136,  0.6484,  0.4287]])

In [13]:
mat1 + vec1

tensor([[0.6591, 0.8944, 1.4099, 0.7080],
        [1.0088, 1.6851, 1.4177, 1.1492],
        [0.1289, 1.2714, 1.2052, 0.9333],
        [0.5642, 1.2547, 1.9160, 0.9805]])

In [14]:
mat2 + vec1

tensor([[1.0241, 1.1403, 1.6678, 0.4886],
        [0.7819, 0.9685, 1.8028, 0.2092],
        [0.6736, 1.6732, 1.5069, 0.2071],
        [0.6192, 1.0784, 1.5030, 0.6409],
        [0.8455, 1.1302, 1.8103, 0.7801]])