In [1]:
import torch

In [3]:
d = torch.randn(4, 5)

In [10]:
d

tensor([[-1.1458, -0.4504, -1.0993,  1.1862,  0.0678],
        [ 0.5507, -1.1903, -1.2756,  1.0836, -0.8232],
        [-0.3346,  1.1775, -1.1101,  0.7475, -0.0991],
        [ 1.9490,  1.1388,  0.3922, -0.7807,  1.0173]])

In [4]:
torch.std(d)

tensor(1.0125)

In [5]:
torch.std(d, dim=0)

tensor([1.3250, 1.1817, 0.7811, 0.9127, 0.7573])

In [6]:
torch.std(d, dim=1)

tensor([0.9644, 1.0784, 0.9042, 1.0162])

In [7]:
torch.var(d)

tensor(1.0252)

In [8]:
torch.var(d, dim=0)

tensor([1.7557, 1.3963, 0.6102, 0.8330, 0.5735])

In [9]:
torch.var(d, dim=1)

tensor([0.9301, 1.1629, 0.8176, 1.0328])