In [1]:
import torch

In [2]:
torch.tensor

<function torch._VariableFunctionsClass.tensor>

In [3]:
t_c = torch.tensor([0.5, 14.0, 15.0, 28.0, 11.0, 8.0, 3.0, -4.0, 6.0, 13.0, 21.0])
t_u = torch.tensor([35.7, 55.9, 58.2, 81.9, 56.3, 48.9, 33.9, 21.8, 48.4, 60.4, 68.4])

In [4]:
t_c

tensor([ 0.5000, 14.0000, 15.0000, 28.0000, 11.0000,  8.0000,  3.0000, -4.0000,
         6.0000, 13.0000, 21.0000])

In [5]:
t_u

tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])

In [6]:
def model(t_u, w, b):
    return w * t_u + b

In [7]:
def loss_fn(t_p, t_c):
    squared_diffs = (t_p - t_c) ** 2

    return squared_diffs.mean()

In [8]:
w = torch.ones(1)
b = torch.zeros(1)

In [9]:
t_p = model(t_u, w, b)

In [10]:
t_p

tensor([35.7000, 55.9000, 58.2000, 81.9000, 56.3000, 48.9000, 33.9000, 21.8000,
        48.4000, 60.4000, 68.4000])

In [11]:
loss = loss_fn(t_p, t_c)

In [12]:
loss

tensor(1763.8848)

In [13]:
delta = 0.1

loss_rate_of_change_w = (loss_fn(model(t_u, w + delta, b), t_c) - loss_fn(model(t_u, w - delta, b), t_c)) / (2.0 * delta)

In [14]:
learning_rate = 1e-2

w = w - learning_rate * loss_rate_of_change_w

In [15]:
loss_rate_of_change_b = (loss_fn(model(t_u, w, b + delta), t_c) - loss_fn(model(t_u, w, b - delta), t_c)) / (2.0 * delta)

In [16]:
b = b - learning_rate * loss_rate_of_change_b

In [17]:
b

tensor([46.])