In [38]:
import torch

In [39]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)

In [40]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [41]:
B = A.clone()

In [42]:
B

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [43]:
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [44]:
A.shape

torch.Size([2, 3])

In [45]:
A.sum(axis=0)

tensor([3., 5., 7.])

In [46]:
A.sum(axis=1)

tensor([ 3., 12.])

In [48]:
A.sum(axis=[0, 1])

tensor(15.)

In [49]:
A.sum()

tensor(15.)

In [47]:
A.sum(axis=[0, 1]) == A.sum()

tensor(True)

In [50]:
A.numel()

6