In [38]:
import torch

In [39]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)

In [40]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [41]:
B = A.clone()

In [42]:
B

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [43]:
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [44]:
A.shape

torch.Size([2, 3])

In [45]:
A.sum(axis=0)

tensor([3., 5., 7.])

In [46]:
A.sum(axis=1)

tensor([ 3., 12.])

In [48]:
A.sum(axis=[0, 1])

tensor(15.)

In [49]:
A.sum()

tensor(15.)

In [47]:
A.sum(axis=[0, 1]) == A.sum()

tensor(True)

In [50]:
A.numel()

6

# Non-Reduction Sum

In [56]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [51]:
sum_A = A.sum(axis=1, keepdims=True)

In [52]:
sum_A

tensor([[ 3.],
        [12.]])

In [53]:
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [55]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [58]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

In [59]:
A.cumsum(axis=1)

tensor([[ 0.,  1.,  3.],
        [ 3.,  7., 12.]])

# Dot Products

두 개의 Vectors $$\mathbf{x}, \mathbf{y} \text{ in } \mathbb{R}^{d}$$

Dot product $$\mathbf{x}^{T}\mathbf{y} = \sum_{i=1}^{d}{x_{i}y_{i}}$$ 

In [63]:
x = torch.arange(3, dtype=torch.float32)
y = torch.ones(3, dtype=torch.float32)

In [65]:
x

tensor([0., 1., 2.])

In [64]:
y

tensor([1., 1., 1.])

In [66]:
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [67]:
torch.sum(x * y)

tensor(3.)

# Matrix-Vector Products

$$A = \begin{bmatrix} \mathbf{a_{1}^{T}} \\ \mathbf{a_{2}^{T}} \\ \vdots \\ \mathbf{a_{m}^{T}} \end{bmatrix}$$

> 여기서, 각 $\mathbf{a_{i}}^{T} \in \mathbb{R}^{n}$은 Matrix $\mathbf{A}$의 $i$번째 Row vector를 나타냄.
>
> 즉, 위의 Matrix $\mathbf{A}$는 $m \times n$ 크기의 Matrix

$$\mathbf{a_{i}}^{T}\mathbf{x}:$$

$$\mathbf{Ax} = \begin{bmatrix} \mathbf{a_{1}^{T}} \\ \mathbf{a_{2}^{T}} \\ \vdots \\ \mathbf{a_{m}^{T}} \end{bmatrix}\mathbf{x} = \begin{bmatrix} \mathbf{a_{1}^{T}x} \\ \mathbf{a_{2}^{T}x} \\ \vdots \\ \mathbf{a_{m}^{T}x} \end{bmatrix}.$$

In [68]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

# Matrix-Matrix Multiplication

In [69]:
B = torch.ones(3, 4)

In [70]:
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

# Norms

$$f: \mathbb{R^{n}} \mapsto \mathbb{R}$$

In [71]:
u = torch.tensor([3.0, -4.0])

In [72]:
torch.norm(u)

tensor(5.)

### $l_1$ Norm

$$||x||_1 = \sum_{i=1}^{n}{|x_i|}$$

In [ ]:
torch.abs(u).sum()

### Frobenius Norm

$$||\mathbf{X}||_F = \sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n}{x_{ij}^{2}}}$$

In [73]:
torch.norm(torch.ones((4, 9)))

tensor(6.)