In [2]:
import torch

In [3]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [4]:
second_point

tensor([5., 3.])

In [5]:
second_point.size()

torch.Size([2])

In [6]:
second_point.shape

torch.Size([2])

In [7]:
points.stride()

(2, 1)

In [14]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [15]:
second_point.storage_offset()

2

In [16]:
second_point = points[0]

In [17]:
second_point.storage_offset()

0

In [18]:
second_point.stride()

(1,)

In [19]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0

In [20]:
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [21]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0

In [22]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])